# Generated by Django 5.2.6 on 2025-09-19 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_casa', models.IntegerField(unique=True)),
                ('metros_cuadrados', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('propietario', 'Propietario'), ('alquiler', 'Alquiler'), ('anticretico', 'Anticrético')], max_length=20)),
                ('propietario_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_unidades.unidad')),
            ],
        ),
    ]
